import { useEffect, useState } from "react";
import { api } from "../api";
import type { FixedConcept, FixedRule } from "../types";

const money = new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" });
const frequencyLabel = { daily: "día", monthly: "mes", annual: "año" };
const emptyConcept = { name: "", parentId: "", calculationMode: "simple", costTreatment: "additional", notes: "" };
const emptyRule = { conceptId: "", effectiveFrom: "", effectiveTo: "", amount: "", frequency: "monthly", vatRate: "0", notes: "" };

export function FixedCostsView({ token }: { token: string }) {
  const [concepts, setConcepts] = useState<FixedConcept[]>([]);
  const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [conceptForm, setConceptForm] = useState(emptyConcept); const [conceptEdit, setConceptEdit] = useState<number | null>(null);
  const [ruleForm, setRuleForm] = useState(emptyRule); const [ruleEdit, setRuleEdit] = useState<number | null>(null);
  const showError = (reason: unknown) => setError(reason instanceof Error ? reason.message : "No se pudo completar la operación.");
  const load = () => api<{ concepts: FixedConcept[] }>("/fixed-concepts", token).then((result) => setConcepts(result.concepts)).catch(showError);
  useEffect(() => { void load(); }, [token]); // eslint-disable-line react-hooks/exhaustive-deps
  const success = (text: string) => { setMessage(text); setError(""); void load(); };
  const parents = concepts.filter((item) => item.parent_id === null);
  const editableRules = concepts.filter((item) => item.calculation_mode === "simple");

  const saveConcept = async (event: React.FormEvent) => {
    event.preventDefault(); setError("");
    try { await api(conceptEdit ? `/fixed-concepts/${conceptEdit}` : "/fixed-concepts", token, { method: conceptEdit ? "PUT" : "POST", body: JSON.stringify(conceptForm) }); setConceptForm(emptyConcept); setConceptEdit(null); success("Concepto guardado."); } catch (reason) { showError(reason); }
  };
  const editConcept = (concept: FixedConcept) => { setConceptEdit(concept.id); setConceptForm({ name: concept.name, parentId: concept.parent_id ? String(concept.parent_id) : "", calculationMode: concept.calculation_mode, costTreatment: concept.cost_treatment, notes: concept.notes ?? "" }); };
  const removeConcept = async (concept: FixedConcept) => { if (!confirm(`¿Quitar “${concept.name}” y sus subconceptos?`)) return; try { await api(`/fixed-concepts/${concept.id}`, token, { method: "DELETE" }); success("Concepto retirado."); } catch (reason) { showError(reason); } };
  const saveRule = async (event: React.FormEvent) => {
    event.preventDefault(); setError("");
    try { await api(ruleEdit ? `/fixed-rules/${ruleEdit}` : "/fixed-rules", token, { method: ruleEdit ? "PUT" : "POST", body: JSON.stringify(ruleForm) }); setRuleForm(emptyRule); setRuleEdit(null); success("Regla guardada. Los periodos usarán la vigencia indicada."); } catch (reason) { showError(reason); }
  };
  const editRule = (rule: FixedRule) => { setRuleEdit(rule.id); setRuleForm({ conceptId: String(rule.concept_id), effectiveFrom: rule.effective_from, effectiveTo: rule.effective_to ?? "", amount: String(rule.amount), frequency: rule.frequency, vatRate: String(rule.vat_rate), notes: rule.notes ?? "" }); };
  const removeRule = async (rule: FixedRule) => { if (!confirm("¿Eliminar esta regla de precio?")) return; try { await api(`/fixed-rules/${rule.id}`, token, { method: "DELETE" }); success("Regla eliminada."); } catch (reason) { showError(reason); } };

  return <section><header className="page-header"><div><p className="eyebrow">Configuración</p><h1>Conceptos fijos</h1><p>Aquí solo se configura el coste real para la comunidad. La cuota diaria cobrada a cada vecino se define dentro de cada periodo.</p></div></header>
    {error && <div className="error-box">{error}</div>}{message && <div className="success-box">{message}</div>}
    <div className="two-column fixed-forms">
      <form className="panel" onSubmit={saveConcept}><div className="panel-title"><div><p className="eyebrow">Estructura</p><h2>{conceptEdit ? "Editar concepto" : "Añadir concepto"}</h2></div></div><div className="form-stack"><label>Nombre<input required value={conceptForm.name} onChange={(e) => setConceptForm({ ...conceptForm, name: e.target.value })} /></label>{!conceptEdit && <label>Dentro de otro concepto<select value={conceptForm.parentId} onChange={(e) => setConceptForm({ ...conceptForm, parentId: e.target.value, calculationMode: "simple" })}><option value="">Concepto principal</option>{parents.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label>Forma de cálculo<select disabled={Boolean(conceptForm.parentId)} value={conceptForm.calculationMode} onChange={(e) => setConceptForm({ ...conceptForm, calculationMode: e.target.value })}><option value="simple">Importe único</option><option value="separate">Separado en subconceptos</option></select></label><label>Tratamiento en el cierre<select value={conceptForm.costTreatment} onChange={(e) => setConceptForm({ ...conceptForm, costTreatment: e.target.value })}><option value="additional">Coste adicional a las facturas</option><option value="included">Ya incluido en las facturas</option></select></label><label>Nota informativa<textarea value={conceptForm.notes} onChange={(e) => setConceptForm({ ...conceptForm, notes: e.target.value })} /></label><div className="form-actions"><button className="primary">Guardar concepto</button>{conceptEdit && <button type="button" className="secondary" onClick={() => { setConceptEdit(null); setConceptForm(emptyConcept); }}>Cancelar</button>}</div></div></form>
      <form className="panel" onSubmit={saveRule}><div className="panel-title"><div><p className="eyebrow">Coste y vigencia</p><h2>{ruleEdit ? "Editar regla" : "Nueva regla"}</h2></div></div><div className="form-grid rule-grid"><label>Concepto<select required disabled={Boolean(ruleEdit)} value={ruleForm.conceptId} onChange={(e) => setRuleForm({ ...ruleForm, conceptId: e.target.value })}><option value="">Selecciona…</option>{editableRules.map((item) => <option key={item.id} value={item.id}>{item.parent_name ? `${item.parent_name} · ` : ""}{item.name}</option>)}</select></label><label>Desde<input required type="date" value={ruleForm.effectiveFrom} onChange={(e) => setRuleForm({ ...ruleForm, effectiveFrom: e.target.value })} /></label><label>Hasta (opcional)<input type="date" value={ruleForm.effectiveTo} onChange={(e) => setRuleForm({ ...ruleForm, effectiveTo: e.target.value })} /></label><label>Coste comunidad (€)<input required min="0" step="0.0001" type="number" value={ruleForm.amount} onChange={(e) => setRuleForm({ ...ruleForm, amount: e.target.value })} /></label><label>Periodicidad<select value={ruleForm.frequency} onChange={(e) => setRuleForm({ ...ruleForm, frequency: e.target.value })}><option value="daily">Diario</option><option value="monthly">Mensual</option><option value="annual">Anual</option></select></label><label>IVA (%)<input required min="0" step="0.01" type="number" value={ruleForm.vatRate} onChange={(e) => setRuleForm({ ...ruleForm, vatRate: e.target.value })} /></label><label className="wide">Nota de esta regla<textarea value={ruleForm.notes} onChange={(e) => setRuleForm({ ...ruleForm, notes: e.target.value })} /></label></div><div className="form-actions"><button className="primary">Guardar regla</button>{ruleEdit && <button type="button" className="secondary" onClick={() => { setRuleEdit(null); setRuleForm(emptyRule); }}>Cancelar</button>}</div></form>
    </div>
    <article className="panel"><div className="panel-title"><div><p className="eyebrow">Configuración vigente e histórica</p><h2>{parents.length} conceptos principales</h2></div></div><div className="concept-list">{parents.map((parent) => <ConceptBlock key={parent.id} parent={parent} concepts={concepts} onEditConcept={editConcept} onRemoveConcept={removeConcept} onEditRule={editRule} onRemoveRule={removeRule} />)}</div></article>
  </section>;
}

function ConceptBlock({ parent, concepts, onEditConcept, onRemoveConcept, onEditRule, onRemoveRule }: { parent: FixedConcept; concepts: FixedConcept[]; onEditConcept: (c: FixedConcept) => void; onRemoveConcept: (c: FixedConcept) => void; onEditRule: (r: FixedRule) => void; onRemoveRule: (r: FixedRule) => void }) {
  const children = concepts.filter((item) => item.parent_id === parent.id); const leaves = children.length ? children : [parent];
  return <section className="concept-block"><header><div><h3>{parent.name}</h3><p>{parent.notes || "Sin nota"}</p></div><span className="concept-tag">{parent.cost_treatment === "included" ? "Incluido en factura" : "Coste adicional"}</span><div className="row-actions"><button onClick={() => onEditConcept(parent)}>Editar</button><button onClick={() => onRemoveConcept(parent)}>Quitar</button></div></header>{leaves.map((concept) => <div className="subconcept" key={concept.id}><div className="subconcept-title"><span><b>{concept.name}</b>{concept !== parent && <small>{concept.notes}</small>}</span>{concept !== parent && <div className="row-actions"><button onClick={() => onEditConcept(concept)}>Editar</button></div>}</div>{concept.rules.length ? concept.rules.map((rule) => <div className="rule-row compact-rule" key={rule.id}><span><b>Desde {formatDate(rule.effective_from)}</b><small>{rule.effective_to ? ` hasta ${formatDate(rule.effective_to)}` : " · vigente"}{rule.notes ? ` · ${rule.notes}` : ""}</small></span><span><small>Coste comunidad</small><b>{money.format(rule.amount)} / {frequencyLabel[rule.frequency]} + {rule.vat_rate}% IVA</b></span><div className="row-actions"><button onClick={() => onEditRule(rule)}>Editar</button><button onClick={() => onRemoveRule(rule)}>×</button></div></div>) : <p className="empty-note">Sin reglas de importe.</p>}</div>)}</section>;
}
function formatDate(value: string) { return new Intl.DateTimeFormat("es-ES", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }
