import { useState } from "react";
import { api } from "../api";
import type { Bootstrap, InvoiceType } from "../types";

const money = new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" });
export function InvoicesView({ data, token, onChanged }: { data: Bootstrap; token: string; onChanged: () => void }) {
  const firstType = data.invoiceTypes.find((item) => item.active)?.id ?? 0;
  const [form, setForm] = useState({ invoiceTypeId: String(firstType), invoiceDate: "", amount: "", description: "" });
  const [typeName, setTypeName] = useState(""); const [editingType, setEditingType] = useState<InvoiceType | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { await api("/invoices", token, { method: "POST", body: JSON.stringify(form) }); setForm({ invoiceTypeId: String(firstType), invoiceDate: "", amount: "", description: "" }); onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo guardar la factura."); } finally { setSaving(false); } };
  const saveType = async (event: React.FormEvent) => { event.preventDefault(); try { await api(editingType ? `/invoice-types/${editingType.id}` : "/invoice-types", token, { method: editingType ? "PUT" : "POST", body: JSON.stringify({ name: typeName }) }); setTypeName(""); setEditingType(null); onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo guardar el tipo."); } };
  const remove = async (id: number) => { if (!confirm("¿Eliminar esta factura?")) return; await api(`/invoices/${id}`, token, { method: "DELETE" }); onChanged(); };
  const removeType = async (item: InvoiceType) => { if (!confirm(`¿Quitar el tipo “${item.name}”? Las facturas existentes se conservan.`)) return; await api(`/invoice-types/${item.id}`, token, { method: "DELETE" }); onChanged(); };
  return <section><header className="page-header"><div><p className="eyebrow">Costes del periodo</p><h1>Facturas</h1><p>El cierre incluye las facturas con fecha posterior al inicio y hasta la fecha final, incluida.</p></div></header>{error && <div className="error-box">{error}</div>}
    <div className="two-column invoices-layout"><div><form className="panel invoice-form" onSubmit={submit}><div className="panel-title"><div><p className="eyebrow">Nueva entrada</p><h2>Añadir factura</h2></div></div><label>Tipo<select required value={form.invoiceTypeId} onChange={(e) => setForm({ ...form, invoiceTypeId: e.target.value })}>{data.invoiceTypes.filter((item) => item.active).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Fecha<input required type="date" value={form.invoiceDate} onChange={(e) => setForm({ ...form, invoiceDate: e.target.value })} /></label><label>Importe (€)<input required type="number" min="0" step="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></label><label>Descripción opcional<input value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><button className="primary" disabled={saving}>{saving ? "Guardando…" : "Añadir factura"}</button></form>
      <form className="panel type-form" onSubmit={saveType}><div className="panel-title"><div><p className="eyebrow">Configuración</p><h2>Tipos de factura</h2></div></div><div className="inline-form"><input required placeholder="Nombre del tipo" value={typeName} onChange={(e) => setTypeName(e.target.value)} /><button className="primary">{editingType ? "Guardar" : "Añadir"}</button></div>{editingType && <button type="button" className="text-button" onClick={() => { setEditingType(null); setTypeName(""); }}>Cancelar edición</button>}<div className="type-list">{data.invoiceTypes.filter((item) => item.active).map((item) => <div key={item.id}><span>{item.name}</span><div className="row-actions"><button type="button" onClick={() => { setEditingType(item); setTypeName(item.name); }}>Editar</button><button type="button" onClick={() => void removeType(item)}>Quitar</button></div></div>)}</div></form></div>
      <article className="panel"><div className="panel-title"><div><p className="eyebrow">Histórico</p><h2>{data.invoices.length} facturas</h2></div></div><div className="invoice-list">{data.invoices.map((invoice) => <div key={invoice.id}><span className="invoice-kind">{invoice.invoice_type_name}</span><span><b>{formatDate(invoice.invoice_date)}</b><small>{invoice.description || "Sin descripción"}</small></span><strong>{money.format(invoice.amount)}</strong><button aria-label="Eliminar factura" onClick={() => void remove(invoice.id)}>×</button></div>)}</div></article></div>
  </section>;
}
function formatDate(value: string) { return new Intl.DateTimeFormat("es-ES", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }
